name: OSS Compliance - SBOM + License Scan

on:
  workflow_dispatch:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Project
        run: ./gradlew build -x test || echo "Gradle not used"

      - name: Install SCANOSS + Syft
        run: |
          pip install scanoss pandas openpyxl
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft dir:. --scope all-layers -o json > syft.sbom.json

      - name: Run SCANOSS
        run: scanoss --path . --output scanoss.sbom.spdx.json

      - name: Generate Excel License Report
        run: python3 generate_excel_from_syft_json.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: oss-results
          path: |
            syft.sbom.json
            scanoss.sbom.spdx.json
            compliance-report.xlsx
